version: '3.9'

services:
  db:
    image: mysql
    container_name: delivery_app_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=deliveryapp
    volumes:
      - ./my-db:/var/lib/mysql
