version: '3.9'

services:
  frontend:
    container_name: delivery_app_frontend
    build: ./front-end
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
  backend:
    container_name: delivery_app_api
    build: ./back-end
    ports:
      - 3001:3001
    volumes:
      - ./back-end:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    container_name: delivery_app_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./my-db:/var/lib/mysql
  adminer:
    image: adminer:4.8.1-standalone
    container_name: database_connector
    restart: always
    ports:
      - 8080:8080
