FROM node:16-alpine AS react-app

RUN apk add --no-cache bash

WORKDIR /home/node/app

RUN chown -R node:node /home/node/app

COPY --chown=node:node package.json ./

COPY --chown=node:node package-lock.json ./

RUN npm ci

COPY --chown=node:node . .

USER node

RUN npm run build

FROM nginx:1.23.4-alpine

EXPOSE 80

COPY ./src/nginx/conf.d/default.conf ./etc/nginx/conf.d/default.conf

COPY --from=react-app /home/node/app/build /usr/share/nginx/html
